language: c++
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LANG
- echo $LC_ALL

install: make cmake
script:
- mkdir build && cd build && cmake .. && make