language: c++
sudo: required
dist: bionic 
compiler:
- gcc
os:
- linux
#- osx
before_install:
- echo $LANG
- echo $LANG
- echo $LC_ALL

script:
- mkdir build && cd build && cmake .. && VERBOSE=1 make
