sudo: required
dist: bionic

language: c++

script:
  - export VERBOSE=1
  - mkdir build
  - cd build
  - cmake ..
  - make

matrix:
  include:
    - os: linux
      compiler: clang-6.0
      env:
        - C_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
      # before_install:
      #   - . ./ci/setup_cmake.sh 3.13.2 Linux
      #   - . ./ci/setup_ninja.sh 1.8.2 linux
      #   - . ./ci/setup_libcxx.sh 6.0.0 /usr
    - os: linux
      compiler: clang-7.0
      env:
        - C_COMPILER=clang-7
        - CXX_COMPILER=clang++-7
      addons:
        apt:
          packages:
            - clang-7
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
      # before_install:
      #   - . ./ci/setup_cmake.sh 3.13.2 Linux
      #   - . ./ci/setup_ninja.sh 1.8.2 linux
      #   - . ./ci/setup_libcxx.sh 7.0.0 /usr
    # - os: osx
    #   osx_image: xcode9.4
    #   env:
    #     - C_COMPILER=clang
    #     - CXX_COMPILER=clang++
    #     - CI_CXX_FLAGS='-Wno-unused-command-line-argument -nostdinc++ -isystem /Users/travis/libc++/include/c++/v1'
    #     - CI_LDFLAGS='-L /Users/travis/libc++/lib'
    #   before_install:
    #     - . ./ci/setup_cmake.sh 3.13.2 Darwin
    #     - . ./ci/setup_ninja.sh 1.8.2 mac
    #     - . ./ci/setup_libcxx.sh 7.0.0 /Users/travis/libc++
    # - os: osx
    #   osx_image: xcode10
    #   env:
    #     - C_COMPILER=clang
    #     - CXX_COMPILER=clang++
    #     - CI_CXX_FLAGS='-Wno-unused-command-line-argument -nostdinc++ -isystem /Users/travis/libc++/include/c++/v1'
    #     - CI_LDFLAGS='-L /Users/travis/libc++/lib'
    #   before_install:
    #     - . ./ci/setup_cmake.sh 3.13.2 Darwin
    #     - . ./ci/setup_ninja.sh 1.8.2 mac
    #     - . ./ci/setup_libcxx.sh 7.0.0 /Users/travis/libc++

